services:

  app:
    build: .
    image: sentinel-fraud-engine
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fraudengine?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: fraudengineuser
      SPRING_DATASOURCE_PASSWORD: Fraudenginep@ss
      SPRING_REDIS_HOST: redis
    networks:
      - sentinel-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fraudengine
      MYSQL_USER: fraudengineuser
      MYSQL_PASSWORD: Fraudenginep@ss
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - sentinel-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge